name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enter SSH
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no root@165.232.188.204

      - name: Change to deployment directory
        run: cd ../var/www

      - name: Pull latest changes
        run: git pull origin main

      - name: Build Docker image
        run: docker build -t marketeer .

      - name: Run Docker container
        run: docker run -d -p 80:3000 --name marketeer marketeer

      - name: Wait for deployment
        run: sleep 10

      # - name: Check deployment status
      #   run: curl -I http://165.232.188.204/
