name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    # Configure Git credentials
    - name: Configure Git Credentials
      run: |
        git config --global credential.helper '!f() { echo "username=${ACTIONS_USER}"; echo "password=${ACTIONS_TOKEN}"; }; f'
      env:
        ACTIONS_USER: ${{ secrets.MY_GITHUB_USERNAME }}
        ACTIONS_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    # Your SSH step
    - name: Run sshpass commands
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        pass: ${{ secrets.SERVER_PASS }}
        run: |
          cd ../var/www/marketeer
          git pull origin master
          if docker ps -a | grep -q marketeer; then
            docker stop marketeer
            docker rm marketeer
          fi
          docker build -t marketeer .
          docker run -d -p 80:3000 --name marketeer marketeer
