name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Your SSH step
    - name: Run sshpass commands
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        pass: ${{ secrets.SERVER_PASS }}
        run: |
          cd ../var/www/marketeer
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git pull "$remote_repo" master
          if docker ps -a | grep -q marketeer; then
            docker stop marketeer
            docker rm marketeer
          fi
          docker build -t marketeer .
          docker run -d -p 80:3000 --name marketeer marketeer
