# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Your SSH step
    - name: Run sshpass commands
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        pass: ${{ secrets.SERVER_PASS }}
        run: |
          cd ../var/www
          git pull origin master
          cd marketeer
          if docker ps -a | grep -q marketeer; then
            docker stop marketeer
            docker rm marketeer
          fi
          docker build -t marketeer .
          docker run -d -p 80:3000 --name marketeer marketeer